version: '3'

services:
  ipstool:
    image: 354918384150.dkr.ecr.eu-north-1.amazonaws.com/ipsl-tool:latest
    ports:
      - "80:80"  # Adjust port numbers as needed
    environment:
      - AWS_ACCESS_KEY_ID=$${{ secrets.AWS_ACCESS_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY=$${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - AWS_REGION=$${{ secrets.AWS_REGION }}
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/ipsl-tool
        awslogs-region: $${{ secrets.AWS_REGION }}
        awslogs-stream-prefix: ecs
