version: '3'

services:
  ipstool:
    image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ipsl-tool:latest
    ports:
      - "80:80"  # Adjust port numbers as needed
    environment:
      - ENV_VAR_NAME=value  # Add any environment variables needed for your app
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/ipsl-tool
        awslogs-region: ${{ secrets.AWS_REGION }}
        awslogs-stream-prefix: ecs

