name: Deploy to ECS

on:
  push:
    branches:
      - main  # Trigger on push to main branch (you can change this as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository to get the code and ecs-task-definition.json
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Step 2: Configure AWS CLI with credentials from GitHub secrets
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}
        
      # Step 3: Register ECS Task Definition from the ecs-task-definition.json file
      - name: Register ECS Task Definition
        run: |
          echo "Registering ECS Task Definition..."
          aws ecs register-task-definition \
            --cli-input-json file://ecs-task-definition.json \
            --region ${{ secrets.AWS_REGION }}
        
      # Step 4: Configure ECS CLI and deploy to ECS using Docker Compose
      - name: Deploy to ECS
        run: |
          ecs-cli configure --cluster ipsl-tool-cluster-latest --region ${{ secrets.AWS_REGION }} --default-launch-type FARGATE --config-name ecsConfig
          ecs-cli compose --file docker-compose.yml service up --cluster-config ecsConfig --ecs-profile ecsProfile
